<h3>Workers</h3>
<a href="new"><button type="button" class="btn btn-outline-primary btn-lg">Add new employee</button></a>
<br>
***
<div class="card">
    <table class="table table-striped">
    <thead>
        <tr class="table-warning">
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col">oib</th>
            <th scope="col">Contract</th>
            <th scope="col">IBAN</th>
        </tr>
    </thead>
    
    </table>
</div>