<h3 class="display-3">Employees</h3>
<a href="new"><button type="button" class="btn btn-outline-primary btn-lg">Add new employee</button></a>
<br>
***
<div class="card">
    <table class="table table-striped">
    <thead>
        <tr class="table-warning">
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col">oib</th>
            <th scope="col">Contract</th>
            <th scope="col">IBAN</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
        <tbody>
            <?php foreach($data as $d):?>
                <tr>
                    <td><?=$d->name?></td>
                    <td><?=$d->surname?></td>
                    <td><?=$d->oib?></td>
                    <td><?=$d->contractnumber?></td>
                    <td><?=$d->iban?></td>
                    <td>
                        <a href="<?=App::config('url')?>worker/update<?=$d->id?>"><i class="bi bi-pencil-square"></i></a>
                        <a href="change?id=<?=$d->id?>"><i class="bi bi-trash3-fill"></i></a>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>