<h3 class="display-3">Shifts</h3>
<a href="new"><button type="button" class="btn btn-outline-primary btn-lg">Add new shift</button></a>
<br>
***
<div class="card">
    <table class="table table-striped">
    <thead>
        <tr class="table-warning">
            <th scope="col">Name</th>
            <th scope="col">Duration</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
        <tbody>
            <?php foreach($data as $d):?>
                <tr>
                    <td><?=$d->name?></td>
                    <td><?=$d->duration?></td>
                    <td>
                        <a href="<?=App::config('url')?>shift/update<?=$d->id?>"><i class="bi bi-pencil-square"></i></a>
                        <a href=""><i class="bi bi-trash3-fill"></i></a>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>