
<img src="<?=App::config('url')?>public/img/productplast.jpg" class="img-fluid" alt="...">

<div class="container"><hr>
    <div class="container text-center" style="background-color:darkgrey;">
        <h3>Product plast jedan je od vodećih skandinavskih proizvođača vakumski oblikovanih termoplasta. Proizvodimo specijalizirane proizvode izrađene po narudžbi od termoplasta za industriju i druge svrhe. Udio izvoza je značajan i u porastu.
            Tvrtka je osnovana 1972. godine u privatnom je vlasništvu. Položaj 20 km zapadno od Kristiansanda na jugu Norveške omogućuje dobru komunikaciju sa Skandinavijom i ostatkom kontinenta.</h3>
        <hr>
        <h4>Product Plast opremljen je modernom i učinkovitom proizvodnom opremom te kompetentnim zaposlenicima koji mogu riješiti većinu izazova koje tržište zahtijeva.
        <hr>
        <h4>Product Plast ima ambiciozan slogan; ”Pravo rješenje, u pravo vrijeme, s pravom kvalitetom”.
        <hr>
        <h4>Nastojimo to postići kroz posebnu posvećenost 4 glavna područja:<br>
            Visoka kompetentnost, Fleksibilnost, Sigurnost opskrbe, Višak / Čvrstoća
    </div>    
</div>
<hr>
<h3> Menadzment </h3>
<p class="card-text"><small class="text-muted">***</small></p>
<div class="card-group">
    <div class="card">
        <img src="<?=App::config('url')?>public/img/direktor.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Generalni Direktor Jon Trondlag</h5>
            <p class="card-text">Bavi se upravljačkim i izvršnim poslovima u proizvodnim i uslužnim organizacijama i tvrtkama i odgovoran je za poslovanje, ispunjenje ciljeva organizacije, upravljanje ljudima, organizacijskim procesima i financijama.</p>
            
        </div>
    </div>
    <div class="card">
        <img src="<?=App::config('url')?>public/img/prodaja.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Voditelj prodaje Marko Maric</h5>
            <p class="card-text">Glavni postulat prodaje glasi – želite li ostvariti uspjeh u prodaji, potrebno je dovoljnom broju ljudi pomoći da dobiju ono što oni žele. Ako ste ikada nešto pokušali prodati, vjerojatno ste ubrzo shvatili da isti proizvod prodaju i mnogi drugi..</p>
            
        </div>
    </div>
    <div class="card">
        <img src="<?=App::config('url')?>public/img/smjena1.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Voditelj smjene Narko Nikolicic</h5>
            <p class="card-text">Vodi smjenu i radi raspored djelatnika na pojedinim strojevima sa naznakom na što bolju produktivnost. Vodi evidenciju radnog vremena djelatnika u svojoj smjeni. Priprema i vodi proizvodnju prema specifikaciji i u dogovoru s voditeljem proizvodnje, kontrolira rad strojeva i djelatnika.</p>
            
        </div>
    </div>
</div>