<!DOCTYPE html>
<html lang="en">
<head>
    <?php include_once 'includes/head.phtml'; ?>
</head>
    <body style="background-color: black;">
        <div class="container" >
            <div class="container text-center" style="background-color:darkgrey; min-height:500px;">
                <?php include_once 'includes/navbar.phtml'; ?>
                <h1>naslov u predlosku - zajednicki deo stranice</h1>

                <hr>

                <?php echo $content; ?>

                <hr>
                            
            </div>
            <?php include_once 'includes/footer.phtml'; ?>
        </div>
        <?php include_once 'includes/scripts.phtml'; ?>
    </body>
</html>