<h3>Employees on Shifts</h3>
<a href="new"><button type="button" class="btn btn-outline-primary btn-lg">Add new</button></a>
<br>
***
<div class="card">
    <table class="table table-striped">
    <thead>
        <tr class="table-warning">
            <th scope="col">Name</th>
            <th scope="col">Shift</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
        <tbody>
            <?php foreach($data as $d):?>
                <tr>
                    <td><?=$d->ime?> <?=$d->prezime?></td>
                    <td><?=$d->smjena?></td>
                    <td>
                        <a href="change?id=<?=$d->id?>">Update</a>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>