<h3 class="display-3">Products</h3>
<a href="<?=App::config('url')?>product/new"><button type="button" class="btn btn-outline-primary btn-lg">Add new product</button></a>
<br>
***
<div class="card">
    <table class="table table-striped">
    <thead>
        <tr class="table-warning">
            <th scope="col">Name</th>
            <th scope="col">Color</th>
            <?php if(App::admin()): ?>
            <th scope="col">Price (€)</th>
            <th scope="col">Customer</th>
            <th scope="col">Action</th>
            <?php endif; ?>
        </tr>
    </thead>
        <tbody>
            <?php foreach($data as $d):?>
                <tr>
                    <td><?=$d->name?></td>
                    <td><?=$d->color?></td>
                    <?php if(App::admin()): ?>
                    <td><?=$d->price?></td>
                    <td><?=$d->customer?></td>
                    <td>
                        <a href="<?=App::config('url')?>product/change/<?=$d->id?>"><i class="bi bi-pencil-square"></i></a>
                        <a href=""><i class="bi bi-trash3-fill"></i></a>
                    </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>